name: Build Cross-platform

on:
  push:
    branches: [build]
  pull_request:
    branches: [build]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: build

      - name: CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Compile
        run: cmake --build build --config Release

      - name: Prepare package folder (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          mkdir -p dist/byteflip
          cp build/byteflip dist/byteflip/byteflip
          chmod +x dist/byteflip/byteflip
          cp LICENSE dist/byteflip/
          cp README.md dist/byteflip/

      - name: Compress to tar.gz (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            tar -czvf byteflip-linux.tar.gz -C dist byteflip
          else
            tar -czvf byteflip-macos.tar.gz -C dist byteflip
          fi

      - name: Prepare package folder (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir dist\byteflip
          copy build\Release\byteflip.exe dist\byteflip\byteflip.exe
          copy LICENSE dist\byteflip\
          copy README.md dist\byteflip\

      - name: Compress to zip (Windows)
        if: runner.os == 'Windows'
        run: powershell -Command "Compress-Archive -Path dist/byteflip/* -DestinationPath byteflip-windows.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: byteflip-${{ matrix.os }}
          path: |
            byteflip-windows.zip
            byteflip-linux.tar.gz
            byteflip-macos.tar.gz
